server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlinblog
    username: root
    password: dlcndgus
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

